app:
  build: .
  ports:
   - "3000:3000"
  volumes:
   - .:/src
  links:
   - redis
  # command: "bin/nv serve"
  entrypoint: "bin/nv"
  restart: always

redis:
  build: ./redis
  ports:
   - "6379:6379"
  restart: always
